<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'cactus (landscape set)' => $set . '_f100',
	'cactus (landscape set)' => $set . '_f101',
	'cactus (landscape set)' => $set . '_f102',
	'plant (landscape set)' => $set . '_f103',
	'bonsai (landscape set)' => $set . '_f104',
	'flowers (landscape set)' => $set . '_f105',
	'plant (landscape set)' => $set . '_f106',
	'flower (landscape set)' => $set . '_f107',
	'bush (landscape set)' => $set . '_f108',
	'plant (landscape set)' => $set . '_f109',
	'pot-holder (landscape set)' => $set . '_f10a',
	'watering-can (landscape set)' => $set . '_f10b',
	'cactus (landscape set)' => $set . '_f10c',
	'flowers (landscape set)' => $set . '_f10d',
	'tulip (landscape set)' => $set . '_f10e',
	'bamboo (landscape set)' => $set . '_f10f',
	'seeds (landscape set)' => $set . '_f110',
	'cactus (landscape set)' => $set . '_f111',
	'leaves (landscape set)' => $set . '_f112',
	'flowers (landscape set)' => $set . '_f113',
	'plant (landscape set)' => $set . '_f114',
	'palm (landscape set)' => $set . '_f115',
	'orange-tree (landscape set)' => $set . '_f116',
	'leaves (landscape set)' => $set . '_f117',
	'house (landscape set)' => $set . '_f118',
	'watering-can (landscape set)' => $set . '_f119',
	'watering (landscape set)' => $set . '_f11a',
	'flower (landscape set)' => $set . '_f11b',
	'leaves (landscape set)' => $set . '_f11c',
	'flower (landscape set)' => $set . '_f11d',
	'cactus (landscape set)' => $set . '_f11e',
	'cactus (landscape set)' => $set . '_f11f',
	'cactus (landscape set)' => $set . '_f120',
	'glass (landscape set)' => $set . '_f121',
	'bowl (landscape set)' => $set . '_f122',
	'shelf (landscape set)' => $set . '_f123',
	'window (landscape set)' => $set . '_f124',
	'flower (landscape set)' => $set . '_f125',
	'terrarium (landscape set)' => $set . '_f126',
	'terrarium (landscape set)' => $set . '_f127',
	'table (landscape set)' => $set . '_f128',
	'vine (landscape set)' => $set . '_f129',
	'pot (landscape set)' => $set . '_f12a',
	'name (landscape set)' => $set . '_f12b',
	'shovel (landscape set)' => $set . '_f12c',
	'spray (landscape set)' => $set . '_f12d',
	'green-house (landscape set)' => $set . '_f12e',
	'shears (landscape set)' => $set . '_f12f',
	'seeding (landscape set)' => $set . '_f130',
	'lighting (landscape set)' => $set . '_f131'
);