<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(
	'lawn-mower (plants set)' => $set . '_f100',
	'wheelbarrow (plants set)' => $set . '_f101',
	'gardener-1 (plants set)' => $set . '_f102',
	'gardener (plants set)' => $set . '_f103',
	'butterfly (plants set)' => $set . '_f104',
	'scissors-1 (plants set)' => $set . '_f105',
	'scissors (plants set)' => $set . '_f106',
	'8-sprout-1 (plants set)' => $set . '_f107',
	'9-grass (plants set)' => $set . '_f108',
	'0-sprout (plants set)' => $set . '_f109',
	'1-pot (plants set)' => $set . '_f10a',
	'bucket (plants set)' => $set . '_f10b',
	'plant-4 (plants set)' => $set . '_f10c',
	'gloves (plants set)' => $set . '_f10d',
	'boot (plants set)' => $set . '_f10e',
	'ladybug (plants set)' => $set . '_f10f',
	'fertilizer (plants set)' => $set . '_f110',
	'seeds (plants set)' => $set . '_f111',
	'leaf (plants set)' => $set . '_f112',
	'sunflower (plants set)' => $set . '_f113',
	'bonsai (plants set)' => $set . '_f114',
	'plant-3 (plants set)' => $set . '_f115',
	'plant-2 (plants set)' => $set . '_f116',
	'plant-1 (plants set)' => $set . '_f117',
	'plant (plants set)' => $set . '_f118',
	'cactus-4 (plants set)' => $set . '_f119',
	'cactus-3 (plants set)' => $set . '_f11a',
	'cactus-2 (plants set)' => $set . '_f11b',
	'cactus-1 (plants set)' => $set . '_f11c',
	'cactus (plants set)' => $set . '_f11d',
	'sprayer-1 (plants set)' => $set . '_f11e',
	'sprayer (plants set)' => $set . '_f11f',
	'rake (plants set)' => $set . '_f120',
	'shovel (plants set)' => $set . '_f121',
	'watering-can (plants set)' => $set . '_f122',
	'flower-4 (plants set)' => $set . '_f123',
	'flower-3 (plants set)' => $set . '_f124',
	'flower-2 (plants set)' => $set . '_f125',
	'flower-1 (plants set)' => $set . '_f126',
	'flower (plants set)' => $set . '_f127'
);